### ISSUE TITLE
.NET 5 / .NET Standard

### ISSUE THREAD

**Issue by JordanMarr** [Jlobblet/Fugit#3]
I just tried to pull Fugit into my unit test project which is still .NET Core 3.1 (upgrading to .NET 5 is further down on my backlog). Since Fugit targets .NET 5, it's a no go for now.

Unless you specifically require .NET 5 features for Fugit, you should consider targeting .NET Standard instead as this will allow it to be consumed by many more projects.

**Comment by Jlobblet** [comment]
This is a very good point. I'm using a few .NET 5 features (e.g. below) but I can remove them without too much work, I think.
https://github.com/Jlobblet/Fugit/blob/4e406ea0d1a6449d077f71721288e83029ab4873/src/Fugit/DayOfWeek.fs#L16-L19

**Comment by JordanMarr** [comment]
I _think_ you should still be able to use string interpolation with netstandard since you are using FSharp.Core 5.

**Comment by Jlobblet** [comment]
Fugit now targets .NET Standard 2.1 as of f56dad7e7595f5860b299c0509230e868bc36c15, tests run on .NET 5.0 and .NET Core 3.1 as of eb927e13d3bf6220a9353862429bb2e5f869c218 and after a brief grapple with CI, version 0.4.0 is now being validated by NuGet.

**Comment by Jlobblet** [comment]
0.4.0 is now validated and indexed on NuGet (https://www.nuget.org/packages/Fugit/0.4.0). Closing.
